[package]
name = "ad-hoc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
rust_decimal = { version = "1", features = ["maths", "serde-float"] }
ethers = "2"
